"""Colocated unit tests for the engines-drift decision (isolation — pure text in/out)."""
from checks.engines_drift.decide import drift, parse_pins


def test_parse_pins_reads_name_and_version():
    assert parse_pins("pytest==9.1.1\ncoverage==7.15.2\n") == {"pytest": "9.1.1", "coverage": "7.15.2"}


def test_parse_pins_ignores_hash_and_comment_and_header_lines():
    text = (
        "# This file was autogenerated by uv\n"
        "pytest==9.1.1 \\\n"
        "    --hash=sha256:deadbeef \\\n"
        "    --hash=sha256:cafef00d\n"
        "    # via something\n"
    )
    assert parse_pins(text) == {"pytest": "9.1.1"}


def test_parse_pins_normalizes_underscores_and_dots_in_names():
    assert parse_pins("cosmic_ray==8.4.6\n") == {"cosmic-ray": "8.4.6"}
    assert parse_pins("cosmic-ray==8.4.6\n") == {"cosmic-ray": "8.4.6"}


def test_parse_pins_stops_the_version_at_an_environment_marker():
    assert parse_pins('tomli==2.0.1 ; python_version < "3.11"\n') == {"tomli": "2.0.1"}


def test_no_drift_when_the_pins_match():
    lock = "pytest==9.1.1\ncoverage==7.15.2\n"
    assert drift(lock, lock) == []


def test_a_changed_version_is_reported_old_to_new():
    assert drift("pytest==9.1.1\n", "pytest==9.2.0\n") == ["pytest: 9.1.1 → 9.2.0"]


def test_a_package_only_in_latest_is_an_addition():
    assert drift("pytest==9.1.1\n", "pytest==9.1.1\nnewdep==1.0\n") == ["newdep: — → 1.0"]


def test_a_package_only_in_the_committed_lock_is_a_removal():
    assert drift("pytest==9.1.1\ngone==2.0\n", "pytest==9.1.1\n") == ["gone: 2.0 → —"]


def test_drift_lines_are_sorted_by_name():
    committed = "zeta==1.0\nalpha==1.0\n"
    latest = "zeta==2.0\nalpha==2.0\n"
    assert drift(committed, latest) == ["alpha: 1.0 → 2.0", "zeta: 1.0 → 2.0"]
