/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function crash(mode: string): void

export declare function print(globs: Array<string>, cwd?: string | undefined | null): PrintResult

export interface PrintResult {
  files: Array<string>
  text: string
}

export declare function run(argv: Array<string>): number

export declare function writeBlock(path: string, id: string, content: string): boolean
